### ISSUE TITLE
Character Builder for OSE fails to show Advanced Fantasy classes since the last update

### ISSUE THREAD

**Issue by Juppstein** [vttred/Necrotic-Gnome-Products-for-Foundry-VTT#2]
### What happened?

Before the last update I was able to select from the Advanced Fanatsy classes on character creation. This is no longer possible and only OSE Basic/Classic are shown.

### Which package?

Advanced Fantasy

### What is the expected behaviour?

When using the character builder Advances Fantasy should be in the rule version selection dropdown

![Workspace 1_226](https://github.com/vttred/Necrotic-Gnome-Products-for-Foundry-VTT/assets/8590930/677efdcf-5173-4239-b44e-1087b650554f)

### Relevant Errors and Warnings

```shell
module.js:7 Illandril's Token Tooltips v3.9.0 Started. To report bugs, go to: https://github.com/illandril/FoundryVTT-token-tooltips/issues
foundry.js:91813 _______________________________________________________________
 _____ ___  _   _ _   _ ____  ______   __ __     _______ _____ 
|  ___/ _ \| | | | \ | |  _ \|  _ \ \ / / \ \   / |_   _|_   _|
| |_ | | | | | | |  \| | | | | |_) \ V /   \ \ / /  | |   | |  
|  _|| |_| | |_| | |\  | |_| |  _ < | |     \ V /   | |   | |  
|_|   \___/ \___/|_| \_|____/|_| \_\|_|      \_/    |_|   |_|  
===============================================================
foundry.js:91823 Foundry VTT | Reestablishing existing session cac3f933cbc3dc5e19421ea4
content-script.js:140 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
content-script.js:141 load Event
foundry.js:8536 Foundry VTT | Connected to server socket using session cac3f933cbc3dc5e19421ea4
libWrapper-api.js:802 libWrapper: Version 1.12.13.0 (71276d1) ready.
foundry.js:8632 Foundry VTT | Initializing Foundry Virtual Tabletop Game
colorSetting.js:632 colorsettings | initializing
init.js:82 SL ready
commons.js:2070 Error: You are accessing CONFIG.Actor.systemDataModels which is deprecated. Please use CONFIG.Actor.dataModels instead.
Deprecated since Version 11
Backwards-compatible support will be removed in Version 13
    at Object.logCompatibilityWarning (commons.js:2059:19)
    at Object.set (foundry.js:91771:21)
    at Object.fn (ose.js:78:16)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at Game.initialize (foundry.js:8635:11)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁libWrapperInit (libWrapper-api.js:805:11)
logCompatibilityWarning @ commons.js:2070
commons.js:2070 Error: You are accessing CONFIG.Item.systemDataModels which is deprecated. Please use CONFIG.Item.dataModels instead.
Deprecated since Version 11
Backwards-compatible support will be removed in Version 13
    at Object.logCompatibilityWarning (commons.js:2059:19)
    at Object.set (foundry.js:91771:21)
    at Object.fn (ose.js:82:15)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at Game.initialize (foundry.js:8635:11)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁libWrapperInit (libWrapper-api.js:805:11)
logCompatibilityWarning @ commons.js:2070
foundry.js:733 Foundry VTT | Error thrown in hooked function '' for hook 'OSE Initialized'
#call @ foundry.js:733
foundry.js:753 ReferenceError: Error thrown in hooked function '' for hook 'OSE Initialized'. OSRCB is not defined
    at Object.fn (classData.js:72:29)
    at #call (foundry.js:730:20)
    at Hooks.call (foundry.js:712:38)
    at Object.fn (init.js:14:9)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at Game.initialize (foundry.js:8635:11)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁libWrapperInit (libWrapper-api.js:805:11)
onError @ foundry.js:753
monks-active-tiles.js:11 monks-active-tiles |  Initializing Monks Active Tiles
monks-enhanced-journal.js:30 monks-enhanced-journal |  Initializing Monks Enhanced Journal
monks-tokenbar.js:28 monks-tokenbar |  Initializing Combat Details
monks-tokenbar.js:28 monks-tokenbar |  initializing
monks-wall-enhancement.js:7 monks-wall-enhancement |  initializing
hooks.mjs:25 
    --------------------------
    itemShop Loaded
    --------------------------
    
nameData.js:2 namedata    ,-----------------------------------
foundry.js:3687 Foundry VTT | Synchronized official game time in 42ms
foundry.js:7682 Foundry VTT | Retrieved and compiled template /systems/ose/dist/templates/actors/character-sheet.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template /systems/ose/dist/templates/actors/monster-sheet.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template /systems/ose/dist/templates/actors/partials/character-header.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template /systems/ose/dist/templates/actors/partials/character-attributes-tab.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template /systems/ose/dist/templates/actors/partials/character-abilities-tab.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template /systems/ose/dist/templates/actors/partials/character-spells-tab.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template /systems/ose/dist/templates/actors/partials/character-inventory-tab.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template /systems/ose/dist/templates/actors/partials/actor-item-summary.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template /systems/ose/dist/templates/actors/partials/character-notes-tab.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template /systems/ose/dist/templates/actors/partials/monster-header.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template /systems/ose/dist/templates/actors/partials/monster-attributes-tab.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template /systems/ose/dist/templates/actors/partials/item-auto-tags-partial.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template /systems/ose/dist/templates/apps/party-sheet.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/dice-calculator/templates/partials/settings.hbs
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/dice-calculator/templates/DiceCreator.hbs
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/dice-calculator/templates/DiceRowSettings.hbs
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/dice-calculator/templates/GeneralSettings.hbs
foundry.js:7533 Foundry VTT | Loaded localization file modules/color-picker/languages/en.json
foundry.js:7533 Foundry VTT | Loaded localization file systems/ose/dist/lang/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/SoundBoard/languages/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/avclient-livekit/lang/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/colorsettings/lang/en.json
foundry.js:7533 Foundry VTT | Loaded localization file lang/en.json
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/dice-calculator/templates/calculator.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/dice-calculator/templates/tray.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/illandril-token-tooltips/templates/menu-customOptions-customRow.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/illandril-token-tooltips/templates/menu-customOptions-standardRow.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/illandril-token-tooltips/templates/menu-persistentTooltips-row.html
foundry.js:7533 Foundry VTT | Loaded localization file modules/dice-so-nice/lang/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/dice-calculator/lang/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/easy-notes/languages/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/fxmaster/lang/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/healthEstimate/lang/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/hey-wait/src/lang/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/ignore-vision/lang/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/illandril-token-tooltips/lang/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/imageretainer/lang/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/item-piles/languages/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/lib-wrapper/lang/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/minimal-ui/lang/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/monks-active-tiles/lang/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/monks-bloodsplats/lang/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/monks-combat-details/lang/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/monks-combat-marker/lang/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/monks-common-display/lang/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/monks-little-details/lang/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/monks-enhanced-journal/lang/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/monks-tokenbar/lang/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/monks-wall-enhancement/lang/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/notelicker/lang/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/ose-encounter-window/lang/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/osr-character-builder/lang/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/osr-helper/lang/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/osr-item-shop/lang/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/perceptive/lang/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/pointer/languages/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/show-token-art/lang/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/token-action-hud-core/languages/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/token-variants/lang/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/window-controls/lang/en.json
foundry.js:7533 Foundry VTT | Loaded localization file modules/token-action-hud-uft/languages/en.json
foundry.js:93012 Foundry VTT | Delaying load of sound modules/SoundBoard/audio/04_00_Dungeon_Backgrounds/RPG_Background_Loops_MP3_Dungeon_Realm_1.mp3 until after first user gesture
ui-layer.mjs:16 Array(9)
foundry.js:5802 Foundry VTT | Rendering SceneNavigation
foundry.js:5802 Foundry VTT | Rendering Notifications
foundry.js:5802 Foundry VTT | Rendering Sidebar
foundry.js:5802 Foundry VTT | Rendering PlayerList
foundry.js:5802 Foundry VTT | Rendering Hotbar
foundry.js:5802 Foundry VTT | Rendering CameraViews
foundry.js:5802 Foundry VTT | Rendering Pause
foundry.js:5802 Foundry VTT | Rendering SceneControls
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/hud/toolclip.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/hud/navigation.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/sidebar.html
foundry.js:5802 Foundry VTT | Rendering ChatLog
foundry.js:5802 Foundry VTT | Rendering CombatTracker
foundry.js:5802 Foundry VTT | Rendering Settings
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/user/players.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/hud/hotbar.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/hud/camera-views.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/hud/pause.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/hud/controls.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/partials/document-partial.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/folder-partial.html
foundry.js:5802 Foundry VTT | Rendering ActorDirectory
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/partials/document-partial.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/folder-partial.html
foundry.js:5802 Foundry VTT | Rendering CardsDirectory
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/partials/pack-partial.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/folder-partial.html
foundry.js:5802 Foundry VTT | Rendering CompendiumDirectory
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/partials/document-partial.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/folder-partial.html
foundry.js:5802 Foundry VTT | Rendering ItemDirectory
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/partials/document-partial.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/folder-partial.html
foundry.js:5802 Foundry VTT | Rendering JournalDirectory
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/partials/playlist-partial.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/folder-partial.html
foundry.js:5802 Foundry VTT | Rendering PlaylistDirectory
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/scene-partial.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/folder-partial.html
foundry.js:5802 Foundry VTT | Rendering SceneDirectory
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/partials/document-partial.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/folder-partial.html
foundry.js:5802 Foundry VTT | Rendering RollTableDirectory
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/chat-log.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/settings.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/combat-tracker.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/document-directory.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/document-directory.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/compendium-directory.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/document-directory.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/document-directory.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/playlists-directory.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/document-directory.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/document-directory.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/chat-message.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template /systems/ose/dist/templates/chat/license.html
foundry.js:73104 Foundry VTT | Fonts loaded and ready.
foundry.js:23746 Foundry VTT | Viewing Scene Die Taverne zwischen den Welten
foundry.js:26632 Foundry VTT | Drawing game canvas for scene Die Taverne zwischen den Welten
foundry.js:29359 Foundry VTT | Loading 65 Assets
foundry.js:34911 Foundry VTT | Drawing the WeatherEffects canvas layer
foundry.js:34911 Foundry VTT | Drawing the ParticleEffectsLayer canvas layer
foundry.js:34911 Foundry VTT | Drawing the CanvasBackgroundAlterationEffects canvas layer
foundry.js:34911 Foundry VTT | Drawing the CanvasIlluminationEffects canvas layer
foundry.js:34911 Foundry VTT | Drawing the CanvasColorationEffects canvas layer
foundry.js:34911 Foundry VTT | Drawing the CanvasVisibility canvas layer
worker.js:73 Worker Compressor | Initialized Worker
foundry.js:34911 Foundry VTT | Drawing the GridLayer canvas layer
foundry.js:34911 Foundry VTT | Drawing the DrawingsLayer canvas layer
foundry.js:34911 Foundry VTT | Drawing the TemplateLayer canvas layer
foundry.js:34911 Foundry VTT | Drawing the TilesLayer canvas layer
foundry.js:34911 Foundry VTT | Drawing the WallsLayer canvas layer
foundry.js:34911 Foundry VTT | Drawing the TokenLayer canvas layer
foundry.js:34911 Foundry VTT | Drawing the SoundsLayer canvas layer
foundry.js:34911 Foundry VTT | Drawing the LightingLayer canvas layer
foundry.js:34911 Foundry VTT | Drawing the NotesLayer canvas layer
foundry.js:34911 Foundry VTT | Drawing the ControlsLayer canvas layer
foundry.js:34911 Foundry VTT | Drawing the SpecialEffectsLayer canvas layer
foundry.js:5802 Foundry VTT | Rendering HeadsUpDisplay
ui-layer.mjs:16 Array(9)
HealthMonitor.js:21 Health Estimate | Error on function getActorHealth(). Token Name: "Salmissra". ID: "y41CNnZAVLGby78g". Type: "character". Error: Token's fraction is not valid, it probably doesn't have a numerical HP or Max HP value.
    at HealthEstimate.getFraction (logic.js:233:10)
    at getActorHealth (HealthMonitor.js:12:47)
    at addCharacter (HealthMonitor.js:38:38)
    at Array.forEach (<anonymous>)
    at Object.onCanvasReady [as fn] (hooks.js:30:10)
    at #call (foundry.js:730:20)
    at Hooks.call (foundry.js:712:38)
    at Canvas.draw (foundry.js:26694:11)
    at async Scene.view (foundry.js:23747:7)
    at async Scene.sceneView (monks-common-display.js:264:26)
    at async Game.initializeCanvas (foundry.js:8895:20)
    at async Game.setupGame (foundry.js:8729:5)
    at async Game._initializeGameView (foundry.js:9990:5)
    at async Game.initialize (foundry.js:8650:5)
getActorHealth @ HealthMonitor.js:21
module.js:7 Illandril's Token Tooltips v3.9.0 Settings Initialized - already on 1
system-hooks.mjs:5 register system hooks
settings.js:351 Token Action HUD | SystemHandler.doRegisterSettings is deprecated. Use SystemHandler.registerSettings
registerSettingsCore @ settings.js:351
hooks.mjs:68 osrItemSHop ready
init.js:172 osr-helper ready
foundry.js:92441 Foundry VTT | Activating pending audio playback with user gesture.
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/hud/hud.html
init.js:43 Uncaught (in promise) TypeError: OSE.util.runFirstLoadSplash is not a function
    at Object.fn (init.js:43:14)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at Game.setupGame (foundry.js:8746:11)
    at async Game._initializeGameView (foundry.js:9990:5)
    at async Game.initialize (foundry.js:8650:5)
init.js:26 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'classic')
    at Object.fn (init.js:26:31)
livekit-client.esm.mjs:17307 silence detected on local audio track
(anonymous) @ livekit-client.esm.mjs:17307
Show 1 more frame
Show less
foundry.js:5802 Foundry VTT | Rendering TokenBar
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/block.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/block.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/block.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/block.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/block.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/block.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/block.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/block.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/card.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/scroll.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/encounter.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/read-aloud.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/ose-encounter-window/templates/partials/monster-card.hbs
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/osr-helper/templates/active-effect/partials/effect-card.hbs
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/osr-helper/templates/active-effect/partials/new-effect-card.hbs
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/osr-helper/templates/active-effect/partials/effects-list-tab.hbs
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/osr-helper/templates/active-effect/partials/create-effect-tab.hbs
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/osr-helper/templates/active-effect/partials/saved-effect-card.hbs
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/pointer/templates/designer.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/token-action-hud-core/templates/action.hbs
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/token-action-hud-core/templates/custom-style-form.hbs
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/token-action-hud-core/templates/group.hbs
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/token-action-hud-core/templates/hud.hbs
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/token-action-hud-core/templates/list-group.hbs
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/token-action-hud-core/templates/settings.hbs
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/token-action-hud-core/templates/tab-group.hbs
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/token-action-hud-core/templates/tag-dialog-group.hbs
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/token-action-hud-core/templates/tag-dialog-hud.hbs
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/token-action-hud-core/templates/tag-dialog-top-level-group.hbs
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/SoundBoard/templates/partials/packagecard.hbs
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/osr-item-shop/templateData/item-shop/partials/shop-header.hbs
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/osr-item-shop/templateData/item-shop/partials/shop-footer.hbs
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/osr-item-shop/templateData/item-shop/partials/buy-tab.hbs
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/osr-item-shop/templateData/item-shop/partials/actor-buy-tab.hbs
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/osr-item-shop/templateData/item-shop/partials/sell-tab.hbs
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/osr-item-shop/templateData/item-shop/partials/pack-tab.hbs
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/osr-item-shop/templateData/item-shop/partials/header.hbs
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/osr-item-shop/templateData/config-tab/config-tab.hbs
foundry.js:7682 Foundry VTT | Retrieved and compiled template ./modules/monks-tokenbar/templates/tokenbar.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/dialog.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/dialog.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/dialog.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/dialog.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/dialog.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/dialog.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/dialog.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/dialog.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/dialog.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/dialog.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/dialog.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/dialog.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/dialog.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/dialog.html
main.js:55 Image retainer detected 0 patch files in imageretainer/ose
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/panel.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/panel.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/panel.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/panel.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/panel.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/panel.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/panel.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/panel.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/panel.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/panel.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/panel.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/panel.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/panel.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/monks-enhanced-journal/templates/apsjournal/panel.html
system-manager.js:32 Token Action HUD | SystemHandler.doRegisterDefaultFlags is deprecated. Use SystemHandler.registerDefaults
registerDefaultsCore @ system-manager.js:32
system-manager.js:69 Token Action HUD | SystemHandler.doGetActionHandler is deprecated. Use SystemHandler.getActionHandler
getActionHandlerCore @ system-manager.js:69
system-manager.js:110 Token Action HUD | SystemHandler.doGetRollHandler is deprecated. Use SystemHandler.getRollHandler
getRollHandlerCore @ system-manager.js:110
init.js:337 OSE Helper Items Added
foundry.js:68326 Foundry Virtual Tabletop requires a minimum screen resolution of 1024px by 700px or greater. Your display currently has an effective resolution of 1366px by 630px, as a result many features of the software may not work properly.
fetch @ foundry.js:68326
foundry.js:5802 Foundry VTT | Rendering H
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/app-window.html
init.js:283 true
hooks.mjs:248 Object He H
foundry.js:5802 Foundry VTT | Rendering osrCharacterBuilder
foundry.js:7682 Foundry VTT | Retrieved and compiled template modules/osr-character-builder/template/character-builder/character-builder.hbs
foundry.js:5802 Foundry VTT | Rendering SupportDetails
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/apps/parts/support-details-report.html
foundry.js:7682 Foundry VTT | Retrieved and compiled template templates/sidebar/apps/support-details.html
foundry.js:68326 Report Copied
foundry.js:5802 Foundry VTT | Rendering osrCharacterBuilder
```

### Additional Support Details

Foundry Virtual Tabletop: Version 11 Stable, 11.315
Game System: ose, 1.10.2
Active Modules: 44
Performance Mode: 2

OS: Unknown
Client: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
GPU: ANGLE (NVIDIA Corporation, NVIDIA GeForce RTX 2060/PCIe/SSE2, OpenGL 4.5.0)
Max Texture Size: 32768

Scene: 9200 x 6800 | Grid Size: 200 | Padding Percentage: 0.25
Walls: 134 | Ambient Lights: 8 | Ambient Sounds: 0 | Tiles: 2 | Tokens: 14

Actors: 72 | Items: 12 | Journal Entries: 16 | Rollable Tables: 19 |
Playlists: 6 | Compendium Packs: 60 | Chat Messages: 133

### Foundry VTT Core Version

V11

### Old-School Essentials Core Version

1.10.2

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jon-peel** [comment]
@Juppstein, or @anthonyronda 
This might be a stupid question:  I am new to Foundation, and I got and added OSE AF to it.

How do I build a character?
Or is there a tutorial somewhere on how to configure and use OSE AF. 
I am not figuring this out.

**Comment by Juppstein** [comment]
> [@Juppstein](https://github.com/Juppstein), or [@anthonyronda](https://github.com/anthonyronda) This might be a stupid question: I am new to Foundation, and I got and added OSE AF to it.
> 
> How do I build a character? Or is there a tutorial somewhere on how to configure and use OSE AF. I am not figuring this out.

First off, you should head over to [https://github.com/NecroticGnome/ose-foundry-core](https://github.com/NecroticGnome/ose-foundry-core) because this repo here is not updated anymore. 

OSE is pretty simple in that regard. You just enter the values into the fields of the character and that's it.  So you go to actors, click create actor, give it a name and then it will open the character sheet for you where you enter your stats. The you either create class abilities manually or you drag them from a compendium on a character.

The other method would be to install the OSR Character Creator module and use that one for char creation. It has a nice little UI that allows selecting class, race and starting equipment. It also allows rolling attribute stats during that process as well. Try it out, it is pretty neat.
